### ISSUE TITLE
Plugin does not send to server

### ISSUE THREAD

**Issue by TJJP** [BiscuitSoftware/SlingShot#4]
I have two fall back servers set up and when on a third server, I kick myself, it will not take me back to the hub or creative server! I have attached the `target-list`
![image](https://user-images.githubusercontent.com/61469514/88421674-f4060a80-cdb6-11ea-86d9-5dfe6f11996a.png)

**Comment by PenguThePenguin** [comment]
you need to put it in "", like this:
target-list:
- "hub"
- "creative"

Make sure you read the docs before you make an issue next time

**Comment by TJJP** [comment]
I updated the target-list it still just kicks me from the network and says this message: 
![image](https://user-images.githubusercontent.com/61469514/107979258-43e33380-6f8c-11eb-9d85-6fa86265770f.png)

**Comment by hi-im-vika** [comment]
@TJJP, not sure if this still relevant, but I fixed my issue by increasing the amount of time before the plugin considers a server down. I changed mine from 25 ms to 300 ms.
```yaml
# How long should SlingShot wait for a response from the target server before assuming it is offline?
# timeout: 25 #ms
timeout: 300 #ms
```
Hope that works for you!

**Comment by TJJP** [comment]
I was able to find another plugin that worked for me, but I will keep that in mind for the future. Thanks!
